Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1246', '201604 - REGULAR - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1246', '201604 - REGULAR - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1246', '201604 - REGULAR - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1246', '201604 - REGULAR - 1 IRD PLATA + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
	
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1249', '201604 - REGULAR - 1 PLUS HD - TC.pdf', 0, 7, 
	0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1249', '201604 - REGULAR - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS		
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1249', '201604 - REGULAR - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1249', '201604 - REGULAR - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1250', '201604 - REGULAR - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1250', '201604 - REGULAR - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1250', '201604 - REGULAR - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1250', '201604 - REGULAR - 1 IRD PLATA + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1251', '201604 - CORPORATIVO DIRECTA - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1251', '201604 - CORPORATIVO DIRECTA - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1252', '201604 - CORPORATIVO DIRECTA - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1252', '201604 - CORPORATIVO DIRECTA - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1253', '201604 - CORPORATIVO DIRECTA - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1253', '201604 - CORPORATIVO DIRECTA - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1256', '201604 - CORPORATIVO DIRECTA - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1256', '201604 - CORPORATIVO DIRECTA - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1257', '201604 - CORPORATIVO DIRECTA - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1257', '201604 - CORPORATIVO DIRECTA - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1258', '201604 - CORPORATIVO DIRECTA - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1258', '201604 - CORPORATIVO DIRECTA - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1259', '201604 - CORPORATIVO DIRECTA - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1259', '201604 - CORPORATIVO DIRECTA - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1262', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1262', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1262', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1262', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1263', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1263', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1263', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1263', '201604 - CORPORATIVO INDIRECTA - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1264', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX - TC.pdf', 0, 7, 
	0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1264', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
	1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1264', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX - EF.pdf', 0, 9, 
	0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1264', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
	1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1265', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX - TC.pdf', 0, 7, 
	0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1265', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
	1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1265', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX - EF.pdf', 0, 9, 
	0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1265', '201604 - CORPORATIVO INDIRECTA - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
	1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1268', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1268', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1268', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1268', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1269', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1269', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1269', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1269', '201604 - CORPORATIVO INDIRECTA - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1270', '201604 - EMPLEADOS RED - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1270', '201604 - EMPLEADOS RED - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1270', '201604 - EMPLEADOS RED - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1270', '201604 - EMPLEADOS RED - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1271', '201604 - EMPLEADOS RED - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1271', '201604 - EMPLEADOS RED - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1271', '201604 - EMPLEADOS RED - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1271', '201604 - EMPLEADOS RED - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1272', '201604 - EMPLEADOS RED - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1272', '201604 - EMPLEADOS RED - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1272', '201604 - EMPLEADOS RED - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1272', '201604 - EMPLEADOS RED - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1273', '201604 - EMPLEADOS RED - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1273', '201604 - EMPLEADOS RED - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1273', '201604 - EMPLEADOS RED - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1273', '201604 - EMPLEADOS RED - 1 IRD PLATA + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1274', '201604 - EMPLEADOS MAM - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1274', '201604 - EMPLEADOS MAM - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1274', '201604 - EMPLEADOS MAM - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1274', '201604 - EMPLEADOS MAM - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1275', '201604 - MDU - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1275', '201604 - MDU - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1275', '201604 - MDU - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1275', '201604 - MDU - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1276', '201604 - MDU - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1276', '201604 - MDU - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1276', '201604 - MDU - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1276', '201604 - MDU - 1 IRD PLATA + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1279', '201604 - REFERIDOS - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1279', '201604 - REFERIDOS - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1280', '201604 - REFERIDOS - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1280', '201604 - REFERIDOS - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1281', '201604 - MDU - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1281', '201604 - MDU - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1281', '201604 - MDU - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1281', '201604 - MDU - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1282', '201604 - MDU - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1282', '201604 - MDU - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1282', '201604 - MDU - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1282', '201604 - MDU - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1283', '201604 - MDU - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1283', '201604 - MDU - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1283', '201604 - MDU - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1283', '201604 - MDU - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1284', '201604 - MDU - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1284', '201604 - MDU - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1284', '201604 - MDU - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1284', '201604 - MDU - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1287', '201604 - MDU - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1287', '201604 - MDU - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1287', '201604 - MDU - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1287', '201604 - MDU - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1288', '201604 - MDU - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1288', '201604 - MDU - 1 IRD PLATA + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1288', '201604 - MDU - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1288', '201604 - MDU - 1 IRD PLATA + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1289', '201604 - CLUBES - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1289', '201604 - CLUBES - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1289', '201604 - CLUBES - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1289', '201604 - CLUBES - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1290', '201604 - CORPORATIVO DIRECTA - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1290', '201604 - CORPORATIVO DIRECTA - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1291', '201604 - REFERIDOS - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1291', '201604 - REFERIDOS - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1292', '201604 - REFERIDOS - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1292', '201604 - REFERIDOS - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1295', '201604 - REFERIDOS - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1295', '201604 - REFERIDOS - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1296', '201604 - REFERIDOS - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1296', '201604 - REFERIDOS - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1297', '201604 - REFERIDOS - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1297', '201604 - REFERIDOS - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1298', '201604 - REFERIDOS - 1 IRD PLATA - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1298', '201604 - REFERIDOS - 1 IRD PLATA - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1301', '201604 - REGULAR - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1301', '201604 - REGULAR - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1301', '201604 - REGULAR - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1301', '201604 - REGULAR - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1302', '201604 - REGULAR - 1 HD ONLY - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1302', '201604 - REGULAR - 1 HD ONLY + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1302', '201604 - REGULAR - 1 HD ONLY - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1302', '201604 - REGULAR - 1 HD ONLY + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1303', '201604 - REGULAR - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1303', '201604 - REGULAR - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1303', '201604 - REGULAR - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1303', '201604 - REGULAR - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1304', '201604 - REGULAR - 1 IRD MIX - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1304', '201604 - REGULAR - 1 IRD MIX + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1304', '201604 - REGULAR - 1 IRD MIX - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1304', '201604 - REGULAR - 1 IRD MIX + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1307', '201604 - REGULAR - 1 PLUS HD - TC.pdf', 0, 7, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1307', '201604 - REGULAR - 1 PLUS HD + 1 IRD - TC.pdf', 0, 7, 
    1, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1307', '201604 - REGULAR - 1 PLUS HD - EF.pdf', 0, 9, 
    0, 0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_CONTRATOS
   (COD_CAMPAÑA, NOM_ANEXO_PDF, COD_CIUDAD, COD_TIPO_PAGO, ES_2X1, COD_TIPO_TARJETA)
 Values
   ('R1307', '201604 - REGULAR - 1 PLUS HD + 1 IRD - EF.pdf', 0, 9, 
    1, 0);
COMMIT;