Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 1, '201604 - REGULAR - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 2, '201604 - REGULAR - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 3, '201604 - REGULAR - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 4, '201604 - REGULAR - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 5, '201604 - REGULAR - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 6, '201604 - REGULAR - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 7, '201604 - REGULAR - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 1, '201604 - REGULAR - PLATINO EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 2, '201604 - REGULAR - PLATINO EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 3, '201604 - REGULAR - PLATINO EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 4, '201604 - REGULAR - PLATINO EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 5, '201604 - REGULAR - PLATINO EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 6, '201604 - REGULAR - PLATINO EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1247', 7, '201604 - REGULAR - PLATINO EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 1, '201604 - REGULAR - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 2, '201604 - REGULAR - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 3, '201604 - REGULAR - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 4, '201604 - REGULAR - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 5, '201604 - REGULAR - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 6, '201604 - REGULAR - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 7, '201604 - REGULAR - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 1, '201604 - REGULAR - PLATINO EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 2, '201604 - REGULAR - PLATINO EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 3, '201604 - REGULAR - PLATINO EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 4, '201604 - REGULAR - PLATINO EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 5, '201604 - REGULAR - PLATINO EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 6, '201604 - REGULAR - PLATINO EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1248', 7, '201604 - REGULAR - PLATINO EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 1, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 2, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 3, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 4, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 5, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 6, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1254', 7, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 1, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 2, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 3, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 4, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 5, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 6, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1255', 7, '201604 - CORPORATIVO DIRECTA - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 1, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 2, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 3, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 4, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 5, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 6, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1260', 7, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 1, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 2, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 3, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 4, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 5, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 6, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1261', 7, '201604 - CORPORATIVO DIRECTA - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 1, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 2, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 3, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 4, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 5, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 6, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 7, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 1, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 2, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 3, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 4, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 5, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 6, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1266', 7, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 1, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 2, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 3, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 4, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 5, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 6, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 7, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 1, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 2, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 3, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 4, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 5, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 6, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1267', 7, '201604 - CORPORATIVO INDIRECTA - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 1, '201604 - MDU - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 2, '201604 - MDU - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 3, '201604 - MDU - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 4, '201604 - MDU - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 5, '201604 - MDU - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 6, '201604 - MDU - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 7, '201604 - MDU - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 1, '201604 - MDU - PLATINO EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 2, '201604 - MDU - PLATINO EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 3, '201604 - MDU - PLATINO EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 4, '201604 - MDU - PLATINO EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 5, '201604 - MDU - PLATINO EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 6, '201604 - MDU - PLATINO EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1277', 7, '201604 - MDU - PLATINO EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 1, '201604 - MDU - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 2, '201604 - MDU - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 3, '201604 - MDU - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 4, '201604 - MDU - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 5, '201604 - MDU - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 6, '201604 - MDU - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 7, '201604 - MDU - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 1, '201604 - MDU - PLATINO EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 2, '201604 - MDU - PLATINO EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 3, '201604 - MDU - PLATINO EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 4, '201604 - MDU - PLATINO EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 5, '201604 - MDU - PLATINO EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 6, '201604 - MDU - PLATINO EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1278', 7, '201604 - MDU - PLATINO EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 1, '201604 - MDU - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 2, '201604 - MDU - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 3, '201604 - MDU - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 4, '201604 - MDU - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 5, '201604 - MDU - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 6, '201604 - MDU - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 7, '201604 - MDU - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 1, '201604 - MDU - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 2, '201604 - MDU - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 3, '201604 - MDU - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 4, '201604 - MDU - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 5, '201604 - MDU - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 6, '201604 - MDU - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1284', 7, '201604 - MDU - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 1, '201604 - MDU - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 2, '201604 - MDU - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 3, '201604 - MDU - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 4, '201604 - MDU - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 5, '201604 - MDU - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 6, '201604 - MDU - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 7, '201604 - MDU - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 1, '201604 - MDU - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 2, '201604 - MDU - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 3, '201604 - MDU - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 4, '201604 - MDU - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 5, '201604 - MDU - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 6, '201604 - MDU - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1285', 7, '201604 - MDU - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 1, '201604 - REFERIDOS - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 2, '201604 - REFERIDOS - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 3, '201604 - REFERIDOS - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 4, '201604 - REFERIDOS - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 5, '201604 - REFERIDOS - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 6, '201604 - REFERIDOS - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 7, '201604 - REFERIDOS - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 1, '201604 - REFERIDOS - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 2, '201604 - REFERIDOS - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 3, '201604 - REFERIDOS - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 4, '201604 - REFERIDOS - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 5, '201604 - REFERIDOS - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 6, '201604 - REFERIDOS - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1293', 7, '201604 - REFERIDOS - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 1, '201604 - REFERIDOS - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 2, '201604 - REFERIDOS - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 3, '201604 - REFERIDOS - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 4, '201604 - REFERIDOS - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 5, '201604 - REFERIDOS - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 6, '201604 - REFERIDOS - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 7, '201604 - REFERIDOS - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 1, '201604 - REFERIDOS - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 2, '201604 - REFERIDOS - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 3, '201604 - REFERIDOS - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 4, '201604 - REFERIDOS - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 5, '201604 - REFERIDOS - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 6, '201604 - REFERIDOS - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1294', 7, '201604 - REFERIDOS - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 1, '201604 - REFERIDOS - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 2, '201604 - REFERIDOS - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 3, '201604 - REFERIDOS - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 4, '201604 - REFERIDOS - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 5, '201604 - REFERIDOS - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 6, '201604 - REFERIDOS - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 7, '201604 - REFERIDOS - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 1, '201604 - REFERIDOS - PLATINO EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 2, '201604 - REFERIDOS - PLATINO EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 3, '201604 - REFERIDOS - PLATINO EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 4, '201604 - REFERIDOS - PLATINO EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 5, '201604 - REFERIDOS - PLATINO EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 6, '201604 - REFERIDOS - PLATINO EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1299', 7, '201604 - REFERIDOS - PLATINO EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 1, '201604 - REFERIDOS - PLATINO TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 2, '201604 - REFERIDOS - PLATINO TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 3, '201604 - REFERIDOS - PLATINO TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 4, '201604 - REFERIDOS - PLATINO TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 5, '201604 - REFERIDOS - PLATINO TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 6, '201604 - REFERIDOS - PLATINO TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 7, '201604 - REFERIDOS - PLATINO TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 1, '201604 - REFERIDOS - PLATINO EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 2, '201604 - REFERIDOS - PLATINO EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 3, '201604 - REFERIDOS - PLATINO EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 4, '201604 - REFERIDOS - PLATINO EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 5, '201604 - REFERIDOS - PLATINO EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 6, '201604 - REFERIDOS - PLATINO EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1300', 7, '201604 - REFERIDOS - PLATINO EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 1, '201604 - REGULAR - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 2, '201604 - REGULAR - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 3, '201604 - REGULAR - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 4, '201604 - REGULAR - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 5, '201604 - REGULAR - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 6, '201604 - REGULAR - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 7, '201604 - REGULAR - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 1, '201604 - REGULAR - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 2, '201604 - REGULAR - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 3, '201604 - REGULAR - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 4, '201604 - REGULAR - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 5, '201604 - REGULAR - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 6, '201604 - REGULAR - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1305', 7, '201604 - REGULAR - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 1, '201604 - REGULAR - HD ORO NEXUS TC 1.0.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 2, '201604 - REGULAR - HD ORO NEXUS TC 1.1.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 3, '201604 - REGULAR - HD ORO NEXUS TC 1.2.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 4, '201604 - REGULAR - HD ORO NEXUS TC 1.3.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 5, '201604 - REGULAR - HD ORO NEXUS TC 1.4.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 6, '201604 - REGULAR - HD ORO NEXUS TC 1.5.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 7, '201604 - REGULAR - HD ORO NEXUS TC 1.6.pdf', 7, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 1, '201604 - REGULAR - HD ORO NEXUS EF 1.0.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 2, '201604 - REGULAR - HD ORO NEXUS EF 1.1.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 3, '201604 - REGULAR - HD ORO NEXUS EF 1.2.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 4, '201604 - REGULAR - HD ORO NEXUS EF 1.3.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 5, '201604 - REGULAR - HD ORO NEXUS EF 1.4.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 6, '201604 - REGULAR - HD ORO NEXUS EF 1.5.pdf', 9, 
    0);
Insert into DTV_VENTAS_UY.TB_VTA_ANEXOS_NEXUS_PLAT
   (COD_CAMPANA, ID_CONFIGURACION, NOM_ANEXO_PDF, COD_TIPO_PAGO, COD_TIPO_TARJETA)
 Values
   ('R1306', 7, '201604 - REGULAR - HD ORO NEXUS EF 1.6.pdf', 9, 
    0);
COMMIT;